apiVersion: platform.example.com/v1
kind: Service
metadata:
  name: release-control-frontend
  labels:
    system: release-control
spec:
  owner: frontend-team
  type: frontend
  runtime: javascript
  repo: github.com/dsahu1001-git/release-control-frontend
  container:
    port: 8080
    healthPath: /health
  ingress:
    enabled: true
    paths:
      - /
  dependencies:
    services:
      - release-control-backend
  environments:
    dev:
      enabled: true
    stage:
      enabled: true
    prod:
      enabled: false
  observability:
    logs: true
    metrics: false
